
//--  This file was automatically generated by the PowerPoint2Verilog compiler. Please do not change anything and use the compiler instead --//

module PP2VerilogDrawingController(CLOCK,reset,animationCLOCK,wasd,arrows,xPixel,yPixel,VGAr,VGAg,VGAb,mouseX,mouseY,colgeniuses,bouncerVISIBLE,);

input CLOCK;
input animationCLOCK;
input [3:0]wasd;
input [3:0]arrows;
input [9:0]xPixel;
input[8:0]yPixel;
input [10:0]mouseX;
input [10:0]mouseY;
output [7:0]VGAr;
output [7:0]VGAg;
output [7:0]VGAb;
reg [7:0]VGAr;
reg [7:0]VGAg;
reg [7:0]VGAb;
input reset;
input [9:0]bouncerVISIBLE;
output colgeniuses;

always @(*)
begin

	//Writing backgound color
	VGAr = 8'b11111111;
	VGAg = 8'b11111111; 
	VGAb = 8'b11111111; 

	if(yPixel>=einsteinY && yPixel<einsteinY+(156*1) && xPixel>=einsteinX+1 && xPixel<einsteinX+(139*1) && einsteinq[15]==1'b1)
	begin
		VGAr=einsteinq[14:10]*8;
		VGAg=einsteinq[9:5]*8;
		VGAb=einsteinq[4:0]*8;
	end

	//Drawing Solid shape "Basictransparency"
	//   --> Allowed 50% transparent render
	if(xPixel>=BasictransparencyX && xPixel<=BasictransparencyX+130 && yPixel>=BasictransparencyY && yPixel<=BasictransparencyY+68)
	begin
		VGAr = (8'b01110000 + VGAr) / 2;
		VGAg = (8'b10101101 + VGAg) / 2;
		VGAb = (8'b01000111 + VGAb) / 2;
		if(xPixel<BasictransparencyX+3 || xPixel>BasictransparencyX+127 || yPixel<BasictransparencyY+3 || yPixel>BasictransparencyY+65)    //Drawing border
		begin
			VGAr = 8'b11110100;
			VGAg = 8'b10110001;
			VGAb = 8'b10000011;
		end
	end

	if(yPixel>=peterY && yPixel<peterY+(156*1) && xPixel>=peterX+1 && xPixel<peterX+(156*1) && peterq[15]==1'b1)
	begin
		VGAr=peterq[14:10]*8;
		VGAg=peterq[9:5]*8;
		VGAb=peterq[4:0]*8;
	end

	if(bouncerVISIBLE && yPixel>=bouncerY && yPixel<bouncerY+(171*1) && xPixel>=bouncerX+1 && xPixel<bouncerX+(303*1) && bouncerq[15]==1'b1)
	begin
		VGAr=(VGAr+bouncerq[14:10]*8)/2;
		VGAg=(VGAg+bouncerq[9:5]*8)/2;
		VGAb=(VGAb+bouncerq[4:0]*8)/2;
	end

	//Drawing mouse: 
	if(yPixel>=(mouseY+1) && yPixel<(mouseY+2) && xPixel>=(mouseX+3) && xPixel<(mouseX+4)) {VGAr,VGAg,VGAb}={8'b01010010,8'b01001000,8'b00000100};
	if(yPixel>=(mouseY+1) && yPixel<(mouseY+2) && xPixel>=(mouseX+4) && xPixel<(mouseX+6)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+1) && yPixel<(mouseY+2) && xPixel>=(mouseX+6) && xPixel<(mouseX+7)) {VGAr,VGAg,VGAb}={8'b10100100,8'b10010000,8'b00000110};
	if(yPixel>=(mouseY+1) && yPixel<(mouseY+2) && xPixel>=(mouseX+7) && xPixel<(mouseX+9)) {VGAr,VGAg,VGAb}={8'b11011100,8'b11001000,8'b00001000};
	if(yPixel>=(mouseY+1) && yPixel<(mouseY+2) && xPixel>=(mouseX+9) && xPixel<(mouseX+10)) {VGAr,VGAg,VGAb}={8'b11011000,8'b11000100,8'b00001000};
	if(yPixel>=(mouseY+2) && yPixel<(mouseY+3) && xPixel>=(mouseX+3) && xPixel<(mouseX+4)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+2) && yPixel<(mouseY+3) && xPixel>=(mouseX+4) && xPixel<(mouseX+5)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+2) && yPixel<(mouseY+3) && xPixel>=(mouseX+5) && xPixel<(mouseX+6)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+2) && yPixel<(mouseY+3) && xPixel>=(mouseX+6) && xPixel<(mouseX+7)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+2) && yPixel<(mouseY+3) && xPixel>=(mouseX+7) && xPixel<(mouseX+9)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+2) && yPixel<(mouseY+3) && xPixel>=(mouseX+9) && xPixel<(mouseX+10)) {VGAr,VGAg,VGAb}={8'b11010000,8'b10111000,8'b00001000};
	if(yPixel>=(mouseY+2) && yPixel<(mouseY+3) && xPixel>=(mouseX+10) && xPixel<(mouseX+11)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+2) && yPixel<(mouseY+3) && xPixel>=(mouseX+11) && xPixel<(mouseX+12)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+3) && yPixel<(mouseY+4) && xPixel>=(mouseX+2) && xPixel<(mouseX+3)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+3) && yPixel<(mouseY+4) && xPixel>=(mouseX+3) && xPixel<(mouseX+4)) {VGAr,VGAg,VGAb}={8'b10001010,8'b01111100,8'b00000100};
	if(yPixel>=(mouseY+3) && yPixel<(mouseY+4) && xPixel>=(mouseX+4) && xPixel<(mouseX+5)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+3) && yPixel<(mouseY+4) && xPixel>=(mouseX+5) && xPixel<(mouseX+6)) {VGAr,VGAg,VGAb}={8'b01011000,8'b01010010,8'b00000100};
	if(yPixel>=(mouseY+3) && yPixel<(mouseY+4) && xPixel>=(mouseX+6) && xPixel<(mouseX+7)) {VGAr,VGAg,VGAb}={8'b10010000,8'b10000000,8'b00000110};
	if(yPixel>=(mouseY+3) && yPixel<(mouseY+4) && xPixel>=(mouseX+7) && xPixel<(mouseX+8)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+3) && yPixel<(mouseY+4) && xPixel>=(mouseX+8) && xPixel<(mouseX+9)) {VGAr,VGAg,VGAb}={8'b10101000,8'b10101000,8'b10101000};
	if(yPixel>=(mouseY+3) && yPixel<(mouseY+4) && xPixel>=(mouseX+9) && xPixel<(mouseX+10)) {VGAr,VGAg,VGAb}={8'b00010000,8'b01010000,8'b00011010};
	if(yPixel>=(mouseY+3) && yPixel<(mouseY+4) && xPixel>=(mouseX+10) && xPixel<(mouseX+12)) {VGAr,VGAg,VGAb}={8'b11010100,8'b11000000,8'b00001000};
	if(yPixel>=(mouseY+3) && yPixel<(mouseY+4) && xPixel>=(mouseX+12) && xPixel<(mouseX+13)) {VGAr,VGAg,VGAb}={8'b01011000,8'b01010100,8'b00000100};
	if(yPixel>=(mouseY+4) && yPixel<(mouseY+5) && xPixel>=(mouseX+2) && xPixel<(mouseX+3)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+4) && yPixel<(mouseY+5) && xPixel>=(mouseX+3) && xPixel<(mouseX+6)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+4) && yPixel<(mouseY+5) && xPixel>=(mouseX+6) && xPixel<(mouseX+8)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+4) && yPixel<(mouseY+5) && xPixel>=(mouseX+8) && xPixel<(mouseX+9)) {VGAr,VGAg,VGAb}={8'b00110000,8'b11111111,8'b01010010};
	if(yPixel>=(mouseY+4) && yPixel<(mouseY+5) && xPixel>=(mouseX+9) && xPixel<(mouseX+10)) {VGAr,VGAg,VGAb}={8'b00101000,8'b11001100,8'b01000010};
	if(yPixel>=(mouseY+4) && yPixel<(mouseY+5) && xPixel>=(mouseX+10) && xPixel<(mouseX+13)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+5) && yPixel<(mouseY+6) && xPixel>=(mouseX+1) && xPixel<(mouseX+2)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+5) && yPixel<(mouseY+6) && xPixel>=(mouseX+2) && xPixel<(mouseX+7)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+5) && yPixel<(mouseY+6) && xPixel>=(mouseX+7) && xPixel<(mouseX+8)) {VGAr,VGAg,VGAb}={8'b01010100,8'b01001000,8'b00000100};
	if(yPixel>=(mouseY+5) && yPixel<(mouseY+6) && xPixel>=(mouseX+8) && xPixel<(mouseX+9)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+5) && yPixel<(mouseY+6) && xPixel>=(mouseX+9) && xPixel<(mouseX+10)) {VGAr,VGAg,VGAb}={8'b00101100,8'b00101000,8'b00000010};
	if(yPixel>=(mouseY+5) && yPixel<(mouseY+6) && xPixel>=(mouseX+10) && xPixel<(mouseX+11)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+5) && yPixel<(mouseY+6) && xPixel>=(mouseX+11) && xPixel<(mouseX+13)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+6) && yPixel<(mouseY+7) && xPixel>=(mouseX+0) && xPixel<(mouseX+1)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+6) && yPixel<(mouseY+7) && xPixel>=(mouseX+1) && xPixel<(mouseX+2)) {VGAr,VGAg,VGAb}={8'b10000100,8'b01110100,8'b00000100};
	if(yPixel>=(mouseY+6) && yPixel<(mouseY+7) && xPixel>=(mouseX+2) && xPixel<(mouseX+4)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+6) && yPixel<(mouseY+7) && xPixel>=(mouseX+4) && xPixel<(mouseX+6)) {VGAr,VGAg,VGAb}={8'b10100100,8'b10010000,8'b00000110};
	if(yPixel>=(mouseY+6) && yPixel<(mouseY+7) && xPixel>=(mouseX+6) && xPixel<(mouseX+7)) {VGAr,VGAg,VGAb}={8'b10110000,8'b10011100,8'b00000110};
	if(yPixel>=(mouseY+6) && yPixel<(mouseY+7) && xPixel>=(mouseX+7) && xPixel<(mouseX+8)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+6) && yPixel<(mouseY+7) && xPixel>=(mouseX+8) && xPixel<(mouseX+9)) {VGAr,VGAg,VGAb}={8'b11011100,8'b11001100,8'b00001000};
	if(yPixel>=(mouseY+6) && yPixel<(mouseY+7) && xPixel>=(mouseX+9) && xPixel<(mouseX+10)) {VGAr,VGAg,VGAb}={8'b10111010,8'b10101100,8'b00001000};
	if(yPixel>=(mouseY+6) && yPixel<(mouseY+7) && xPixel>=(mouseX+10) && xPixel<(mouseX+11)) {VGAr,VGAg,VGAb}={8'b11011100,8'b11001000,8'b00001000};
	if(yPixel>=(mouseY+6) && yPixel<(mouseY+7) && xPixel>=(mouseX+11) && xPixel<(mouseX+12)) {VGAr,VGAg,VGAb}={8'b11010000,8'b10111010,8'b00001000};
	if(yPixel>=(mouseY+6) && yPixel<(mouseY+7) && xPixel>=(mouseX+12) && xPixel<(mouseX+13)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+7) && yPixel<(mouseY+8) && xPixel>=(mouseX+1) && xPixel<(mouseX+2)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+7) && yPixel<(mouseY+8) && xPixel>=(mouseX+2) && xPixel<(mouseX+6)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+7) && yPixel<(mouseY+8) && xPixel>=(mouseX+6) && xPixel<(mouseX+7)) {VGAr,VGAg,VGAb}={8'b11011100,8'b11001100,8'b00001000};
	if(yPixel>=(mouseY+7) && yPixel<(mouseY+8) && xPixel>=(mouseX+7) && xPixel<(mouseX+8)) {VGAr,VGAg,VGAb}={8'b01010100,8'b01001000,8'b00000100};
	if(yPixel>=(mouseY+7) && yPixel<(mouseY+8) && xPixel>=(mouseX+8) && xPixel<(mouseX+9)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+7) && yPixel<(mouseY+8) && xPixel>=(mouseX+9) && xPixel<(mouseX+10)) {VGAr,VGAg,VGAb}={8'b01101110,8'b01100100,8'b00000100};
	if(yPixel>=(mouseY+7) && yPixel<(mouseY+8) && xPixel>=(mouseX+10) && xPixel<(mouseX+11)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+7) && yPixel<(mouseY+8) && xPixel>=(mouseX+11) && xPixel<(mouseX+12)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+7) && yPixel<(mouseY+8) && xPixel>=(mouseX+12) && xPixel<(mouseX+13)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+7) && yPixel<(mouseY+8) && xPixel>=(mouseX+13) && xPixel<(mouseX+14)) {VGAr,VGAg,VGAb}={8'b11011000,8'b11000100,8'b00001000};
	if(yPixel>=(mouseY+7) && yPixel<(mouseY+8) && xPixel>=(mouseX+14) && xPixel<(mouseX+20)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+7) && yPixel<(mouseY+8) && xPixel>=(mouseX+20) && xPixel<(mouseX+21)) {VGAr,VGAg,VGAb}={8'b11011000,8'b11000100,8'b00001000};
	if(yPixel>=(mouseY+8) && yPixel<(mouseY+9) && xPixel>=(mouseX+1) && xPixel<(mouseX+2)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+8) && yPixel<(mouseY+9) && xPixel>=(mouseX+2) && xPixel<(mouseX+3)) {VGAr,VGAg,VGAb}={8'b01001010,8'b01001010,8'b01001010};
	if(yPixel>=(mouseY+8) && yPixel<(mouseY+9) && xPixel>=(mouseX+3) && xPixel<(mouseX+5)) {VGAr,VGAg,VGAb}={8'b11011000,8'b11000100,8'b00001000};
	if(yPixel>=(mouseY+8) && yPixel<(mouseY+9) && xPixel>=(mouseX+5) && xPixel<(mouseX+6)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+8) && yPixel<(mouseY+9) && xPixel>=(mouseX+6) && xPixel<(mouseX+7)) {VGAr,VGAg,VGAb}={8'b00010000,8'b00010000,8'b00010000};
	if(yPixel>=(mouseY+8) && yPixel<(mouseY+9) && xPixel>=(mouseX+7) && xPixel<(mouseX+8)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+8) && yPixel<(mouseY+9) && xPixel>=(mouseX+8) && xPixel<(mouseX+9)) {VGAr,VGAg,VGAb}={8'b11101100,8'b10100110,8'b01100000};
	if(yPixel>=(mouseY+8) && yPixel<(mouseY+9) && xPixel>=(mouseX+9) && xPixel<(mouseX+10)) {VGAr,VGAg,VGAb}={8'b00101100,8'b00101000,8'b00000010};
	if(yPixel>=(mouseY+8) && yPixel<(mouseY+9) && xPixel>=(mouseX+10) && xPixel<(mouseX+11)) {VGAr,VGAg,VGAb}={8'b11011000,8'b11000100,8'b00001000};
	if(yPixel>=(mouseY+8) && yPixel<(mouseY+9) && xPixel>=(mouseX+11) && xPixel<(mouseX+12)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+8) && yPixel<(mouseY+9) && xPixel>=(mouseX+12) && xPixel<(mouseX+13)) {VGAr,VGAg,VGAb}={8'b11011100,8'b11001010,8'b00001000};
	if(yPixel>=(mouseY+8) && yPixel<(mouseY+9) && xPixel>=(mouseX+13) && xPixel<(mouseX+14)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+8) && yPixel<(mouseY+9) && xPixel>=(mouseX+14) && xPixel<(mouseX+15)) {VGAr,VGAg,VGAb}={8'b01000010,8'b00111010,8'b00000010};
	if(yPixel>=(mouseY+8) && yPixel<(mouseY+9) && xPixel>=(mouseX+15) && xPixel<(mouseX+19)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+8) && yPixel<(mouseY+9) && xPixel>=(mouseX+19) && xPixel<(mouseX+20)) {VGAr,VGAg,VGAb}={8'b11010000,8'b10111010,8'b00001000};
	if(yPixel>=(mouseY+8) && yPixel<(mouseY+9) && xPixel>=(mouseX+20) && xPixel<(mouseX+21)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+9) && yPixel<(mouseY+10) && xPixel>=(mouseX+1) && xPixel<(mouseX+2)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+9) && yPixel<(mouseY+10) && xPixel>=(mouseX+2) && xPixel<(mouseX+3)) {VGAr,VGAg,VGAb}={8'b10010100,8'b10010100,8'b10010100};
	if(yPixel>=(mouseY+9) && yPixel<(mouseY+10) && xPixel>=(mouseX+3) && xPixel<(mouseX+4)) {VGAr,VGAg,VGAb}={8'b01010000,8'b01010000,8'b01010000};
	if(yPixel>=(mouseY+9) && yPixel<(mouseY+10) && xPixel>=(mouseX+4) && xPixel<(mouseX+5)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+9) && yPixel<(mouseY+10) && xPixel>=(mouseX+5) && xPixel<(mouseX+6)) {VGAr,VGAg,VGAb}={8'b11001000,8'b11001000,8'b11001000};
	if(yPixel>=(mouseY+9) && yPixel<(mouseY+10) && xPixel>=(mouseX+6) && xPixel<(mouseX+7)) {VGAr,VGAg,VGAb}={8'b00011110,8'b00011110,8'b00011110};
	if(yPixel>=(mouseY+9) && yPixel<(mouseY+10) && xPixel>=(mouseX+7) && xPixel<(mouseX+8)) {VGAr,VGAg,VGAb}={8'b11000010,8'b11000010,8'b11000010};
	if(yPixel>=(mouseY+9) && yPixel<(mouseY+10) && xPixel>=(mouseX+8) && xPixel<(mouseX+9)) {VGAr,VGAg,VGAb}={8'b10100100,8'b10010000,8'b00000110};
	if(yPixel>=(mouseY+9) && yPixel<(mouseY+10) && xPixel>=(mouseX+9) && xPixel<(mouseX+10)) {VGAr,VGAg,VGAb}={8'b11010100,8'b10111110,8'b00001000};
	if(yPixel>=(mouseY+9) && yPixel<(mouseY+10) && xPixel>=(mouseX+10) && xPixel<(mouseX+12)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+9) && yPixel<(mouseY+10) && xPixel>=(mouseX+12) && xPixel<(mouseX+13)) {VGAr,VGAg,VGAb}={8'b01111100,8'b01101100,8'b00000100};
	if(yPixel>=(mouseY+9) && yPixel<(mouseY+10) && xPixel>=(mouseX+13) && xPixel<(mouseX+14)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+9) && yPixel<(mouseY+10) && xPixel>=(mouseX+14) && xPixel<(mouseX+15)) {VGAr,VGAg,VGAb}={8'b11011100,8'b11001000,8'b00001000};
	if(yPixel>=(mouseY+9) && yPixel<(mouseY+10) && xPixel>=(mouseX+15) && xPixel<(mouseX+18)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+9) && yPixel<(mouseY+10) && xPixel>=(mouseX+18) && xPixel<(mouseX+19)) {VGAr,VGAg,VGAb}={8'b01010100,8'b01001010,8'b00000100};
	if(yPixel>=(mouseY+9) && yPixel<(mouseY+10) && xPixel>=(mouseX+19) && xPixel<(mouseX+21)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+10) && yPixel<(mouseY+11) && xPixel>=(mouseX+3) && xPixel<(mouseX+8)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+10) && yPixel<(mouseY+11) && xPixel>=(mouseX+8) && xPixel<(mouseX+9)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+10) && yPixel<(mouseY+11) && xPixel>=(mouseX+9) && xPixel<(mouseX+10)) {VGAr,VGAg,VGAb}={8'b11011100,8'b11001000,8'b00001000};
	if(yPixel>=(mouseY+10) && yPixel<(mouseY+11) && xPixel>=(mouseX+10) && xPixel<(mouseX+11)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+10) && yPixel<(mouseY+11) && xPixel>=(mouseX+11) && xPixel<(mouseX+12)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+10) && yPixel<(mouseY+11) && xPixel>=(mouseX+12) && xPixel<(mouseX+13)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+10) && yPixel<(mouseY+11) && xPixel>=(mouseX+13) && xPixel<(mouseX+15)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+10) && yPixel<(mouseY+11) && xPixel>=(mouseX+15) && xPixel<(mouseX+18)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+10) && yPixel<(mouseY+11) && xPixel>=(mouseX+18) && xPixel<(mouseX+19)) {VGAr,VGAg,VGAb}={8'b01011000,8'b01010010,8'b00000100};
	if(yPixel>=(mouseY+10) && yPixel<(mouseY+11) && xPixel>=(mouseX+19) && xPixel<(mouseX+20)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+10) && yPixel<(mouseY+11) && xPixel>=(mouseX+20) && xPixel<(mouseX+21)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+11) && yPixel<(mouseY+12) && xPixel>=(mouseX+3) && xPixel<(mouseX+4)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+11) && yPixel<(mouseY+12) && xPixel>=(mouseX+4) && xPixel<(mouseX+5)) {VGAr,VGAg,VGAb}={8'b11010000,8'b10111010,8'b00001000};
	if(yPixel>=(mouseY+11) && yPixel<(mouseY+12) && xPixel>=(mouseX+5) && xPixel<(mouseX+8)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+11) && yPixel<(mouseY+12) && xPixel>=(mouseX+8) && xPixel<(mouseX+9)) {VGAr,VGAg,VGAb}={8'b11011000,8'b11000110,8'b00001000};
	if(yPixel>=(mouseY+11) && yPixel<(mouseY+12) && xPixel>=(mouseX+9) && xPixel<(mouseX+10)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+11) && yPixel<(mouseY+12) && xPixel>=(mouseX+10) && xPixel<(mouseX+11)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+11) && yPixel<(mouseY+12) && xPixel>=(mouseX+11) && xPixel<(mouseX+14)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+11) && yPixel<(mouseY+12) && xPixel>=(mouseX+14) && xPixel<(mouseX+15)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+11) && yPixel<(mouseY+12) && xPixel>=(mouseX+15) && xPixel<(mouseX+18)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+11) && yPixel<(mouseY+12) && xPixel>=(mouseX+18) && xPixel<(mouseX+19)) {VGAr,VGAg,VGAb}={8'b01011000,8'b01010010,8'b00000100};
	if(yPixel>=(mouseY+11) && yPixel<(mouseY+12) && xPixel>=(mouseX+19) && xPixel<(mouseX+21)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+12) && yPixel<(mouseY+13) && xPixel>=(mouseX+4) && xPixel<(mouseX+5)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+12) && yPixel<(mouseY+13) && xPixel>=(mouseX+5) && xPixel<(mouseX+6)) {VGAr,VGAg,VGAb}={8'b01011000,8'b01010100,8'b00000100};
	if(yPixel>=(mouseY+12) && yPixel<(mouseY+13) && xPixel>=(mouseX+6) && xPixel<(mouseX+7)) {VGAr,VGAg,VGAb}={8'b01010100,8'b01001100,8'b00000100};
	if(yPixel>=(mouseY+12) && yPixel<(mouseY+13) && xPixel>=(mouseX+7) && xPixel<(mouseX+9)) {VGAr,VGAg,VGAb}={8'b01010100,8'b01001000,8'b00000100};
	if(yPixel>=(mouseY+12) && yPixel<(mouseY+13) && xPixel>=(mouseX+9) && xPixel<(mouseX+10)) {VGAr,VGAg,VGAb}={8'b01111100,8'b01101100,8'b00000100};
	if(yPixel>=(mouseY+12) && yPixel<(mouseY+13) && xPixel>=(mouseX+10) && xPixel<(mouseX+14)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+12) && yPixel<(mouseY+13) && xPixel>=(mouseX+14) && xPixel<(mouseX+15)) {VGAr,VGAg,VGAb}={8'b01110010,8'b01101000,8'b00000100};
	if(yPixel>=(mouseY+12) && yPixel<(mouseY+13) && xPixel>=(mouseX+15) && xPixel<(mouseX+16)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+12) && yPixel<(mouseY+13) && xPixel>=(mouseX+16) && xPixel<(mouseX+17)) {VGAr,VGAg,VGAb}={8'b10010110,8'b10001010,8'b00000110};
	if(yPixel>=(mouseY+12) && yPixel<(mouseY+13) && xPixel>=(mouseX+17) && xPixel<(mouseX+18)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+12) && yPixel<(mouseY+13) && xPixel>=(mouseX+18) && xPixel<(mouseX+19)) {VGAr,VGAg,VGAb}={8'b00110110,8'b00110100,8'b00000000};
	if(yPixel>=(mouseY+12) && yPixel<(mouseY+13) && xPixel>=(mouseX+19) && xPixel<(mouseX+21)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+12) && yPixel<(mouseY+13) && xPixel>=(mouseX+21) && xPixel<(mouseX+22)) {VGAr,VGAg,VGAb}={8'b10001110,8'b01111110,8'b00000110};
	if(yPixel>=(mouseY+13) && yPixel<(mouseY+14) && xPixel>=(mouseX+6) && xPixel<(mouseX+7)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+13) && yPixel<(mouseY+14) && xPixel>=(mouseX+7) && xPixel<(mouseX+12)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+13) && yPixel<(mouseY+14) && xPixel>=(mouseX+12) && xPixel<(mouseX+13)) {VGAr,VGAg,VGAb}={8'b01111100,8'b01101100,8'b00000100};
	if(yPixel>=(mouseY+13) && yPixel<(mouseY+14) && xPixel>=(mouseX+13) && xPixel<(mouseX+14)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+13) && yPixel<(mouseY+14) && xPixel>=(mouseX+14) && xPixel<(mouseX+15)) {VGAr,VGAg,VGAb}={8'b11011100,8'b11001000,8'b00001000};
	if(yPixel>=(mouseY+13) && yPixel<(mouseY+14) && xPixel>=(mouseX+15) && xPixel<(mouseX+16)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+13) && yPixel<(mouseY+14) && xPixel>=(mouseX+16) && xPixel<(mouseX+17)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+13) && yPixel<(mouseY+14) && xPixel>=(mouseX+17) && xPixel<(mouseX+18)) {VGAr,VGAg,VGAb}={8'b11010100,8'b11000000,8'b00001000};
	if(yPixel>=(mouseY+13) && yPixel<(mouseY+14) && xPixel>=(mouseX+18) && xPixel<(mouseX+19)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+13) && yPixel<(mouseY+14) && xPixel>=(mouseX+19) && xPixel<(mouseX+21)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+13) && yPixel<(mouseY+14) && xPixel>=(mouseX+21) && xPixel<(mouseX+22)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+14) && yPixel<(mouseY+15) && xPixel>=(mouseX+5) && xPixel<(mouseX+6)) {VGAr,VGAg,VGAb}={8'b00101000,8'b00100100,8'b00000010};
	if(yPixel>=(mouseY+14) && yPixel<(mouseY+15) && xPixel>=(mouseX+6) && xPixel<(mouseX+7)) {VGAr,VGAg,VGAb}={8'b10100100,8'b10010000,8'b00000110};
	if(yPixel>=(mouseY+14) && yPixel<(mouseY+15) && xPixel>=(mouseX+7) && xPixel<(mouseX+10)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+14) && yPixel<(mouseY+15) && xPixel>=(mouseX+10) && xPixel<(mouseX+12)) {VGAr,VGAg,VGAb}={8'b10100100,8'b10010000,8'b00000110};
	if(yPixel>=(mouseY+14) && yPixel<(mouseY+15) && xPixel>=(mouseX+12) && xPixel<(mouseX+13)) {VGAr,VGAg,VGAb}={8'b01111100,8'b01101100,8'b00000100};
	if(yPixel>=(mouseY+14) && yPixel<(mouseY+15) && xPixel>=(mouseX+13) && xPixel<(mouseX+14)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+14) && yPixel<(mouseY+15) && xPixel>=(mouseX+14) && xPixel<(mouseX+15)) {VGAr,VGAg,VGAb}={8'b11011100,8'b11001000,8'b00001000};
	if(yPixel>=(mouseY+14) && yPixel<(mouseY+15) && xPixel>=(mouseX+15) && xPixel<(mouseX+16)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+14) && yPixel<(mouseY+15) && xPixel>=(mouseX+16) && xPixel<(mouseX+17)) {VGAr,VGAg,VGAb}={8'b11011000,8'b11000100,8'b00001000};
	if(yPixel>=(mouseY+14) && yPixel<(mouseY+15) && xPixel>=(mouseX+17) && xPixel<(mouseX+18)) {VGAr,VGAg,VGAb}={8'b11010110,8'b11000010,8'b00001000};
	if(yPixel>=(mouseY+14) && yPixel<(mouseY+15) && xPixel>=(mouseX+18) && xPixel<(mouseX+19)) {VGAr,VGAg,VGAb}={8'b01011010,8'b01010000,8'b00000100};
	if(yPixel>=(mouseY+14) && yPixel<(mouseY+15) && xPixel>=(mouseX+19) && xPixel<(mouseX+21)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+14) && yPixel<(mouseY+15) && xPixel>=(mouseX+21) && xPixel<(mouseX+22)) {VGAr,VGAg,VGAb}={8'b11011100,8'b11001000,8'b00001000};
	if(yPixel>=(mouseY+15) && yPixel<(mouseY+16) && xPixel>=(mouseX+2) && xPixel<(mouseX+3)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+15) && yPixel<(mouseY+16) && xPixel>=(mouseX+3) && xPixel<(mouseX+4)) {VGAr,VGAg,VGAb}={8'b01111100,8'b01101100,8'b00000100};
	if(yPixel>=(mouseY+15) && yPixel<(mouseY+16) && xPixel>=(mouseX+4) && xPixel<(mouseX+6)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+15) && yPixel<(mouseY+16) && xPixel>=(mouseX+6) && xPixel<(mouseX+7)) {VGAr,VGAg,VGAb}={8'b10100100,8'b10010000,8'b00000110};
	if(yPixel>=(mouseY+15) && yPixel<(mouseY+16) && xPixel>=(mouseX+7) && xPixel<(mouseX+9)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+15) && yPixel<(mouseY+16) && xPixel>=(mouseX+9) && xPixel<(mouseX+10)) {VGAr,VGAg,VGAb}={8'b10100100,8'b10010000,8'b00000110};
	if(yPixel>=(mouseY+15) && yPixel<(mouseY+16) && xPixel>=(mouseX+10) && xPixel<(mouseX+11)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+15) && yPixel<(mouseY+16) && xPixel>=(mouseX+11) && xPixel<(mouseX+12)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+15) && yPixel<(mouseY+16) && xPixel>=(mouseX+12) && xPixel<(mouseX+13)) {VGAr,VGAg,VGAb}={8'b11011000,8'b11000100,8'b00001000};
	if(yPixel>=(mouseY+15) && yPixel<(mouseY+16) && xPixel>=(mouseX+13) && xPixel<(mouseX+14)) {VGAr,VGAg,VGAb}={8'b01111100,8'b01101100,8'b00000100};
	if(yPixel>=(mouseY+15) && yPixel<(mouseY+16) && xPixel>=(mouseX+14) && xPixel<(mouseX+15)) {VGAr,VGAg,VGAb}={8'b00101000,8'b00100100,8'b00000010};
	if(yPixel>=(mouseY+15) && yPixel<(mouseY+16) && xPixel>=(mouseX+15) && xPixel<(mouseX+18)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+15) && yPixel<(mouseY+16) && xPixel>=(mouseX+18) && xPixel<(mouseX+19)) {VGAr,VGAg,VGAb}={8'b10000110,8'b01111100,8'b00000100};
	if(yPixel>=(mouseY+15) && yPixel<(mouseY+16) && xPixel>=(mouseX+19) && xPixel<(mouseX+21)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+15) && yPixel<(mouseY+16) && xPixel>=(mouseX+21) && xPixel<(mouseX+22)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+16) && yPixel<(mouseY+17) && xPixel>=(mouseX+2) && xPixel<(mouseX+4)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+16) && yPixel<(mouseY+17) && xPixel>=(mouseX+4) && xPixel<(mouseX+5)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+16) && yPixel<(mouseY+17) && xPixel>=(mouseX+5) && xPixel<(mouseX+6)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+16) && yPixel<(mouseY+17) && xPixel>=(mouseX+6) && xPixel<(mouseX+7)) {VGAr,VGAg,VGAb}={8'b10100100,8'b10010000,8'b00000110};
	if(yPixel>=(mouseY+16) && yPixel<(mouseY+17) && xPixel>=(mouseX+7) && xPixel<(mouseX+8)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+16) && yPixel<(mouseY+17) && xPixel>=(mouseX+8) && xPixel<(mouseX+9)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+16) && yPixel<(mouseY+17) && xPixel>=(mouseX+9) && xPixel<(mouseX+10)) {VGAr,VGAg,VGAb}={8'b10100100,8'b10010000,8'b00000110};
	if(yPixel>=(mouseY+16) && yPixel<(mouseY+17) && xPixel>=(mouseX+10) && xPixel<(mouseX+12)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+16) && yPixel<(mouseY+17) && xPixel>=(mouseX+12) && xPixel<(mouseX+13)) {VGAr,VGAg,VGAb}={8'b01110010,8'b01101000,8'b00000100};
	if(yPixel>=(mouseY+16) && yPixel<(mouseY+17) && xPixel>=(mouseX+13) && xPixel<(mouseX+20)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+16) && yPixel<(mouseY+17) && xPixel>=(mouseX+20) && xPixel<(mouseX+22)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+17) && yPixel<(mouseY+18) && xPixel>=(mouseX+3) && xPixel<(mouseX+6)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+17) && yPixel<(mouseY+18) && xPixel>=(mouseX+6) && xPixel<(mouseX+7)) {VGAr,VGAg,VGAb}={8'b10100100,8'b10010000,8'b00000110};
	if(yPixel>=(mouseY+17) && yPixel<(mouseY+18) && xPixel>=(mouseX+7) && xPixel<(mouseX+8)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+17) && yPixel<(mouseY+18) && xPixel>=(mouseX+8) && xPixel<(mouseX+12)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+17) && yPixel<(mouseY+18) && xPixel>=(mouseX+12) && xPixel<(mouseX+13)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+17) && yPixel<(mouseY+18) && xPixel>=(mouseX+13) && xPixel<(mouseX+14)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+17) && yPixel<(mouseY+18) && xPixel>=(mouseX+14) && xPixel<(mouseX+15)) {VGAr,VGAg,VGAb}={8'b10111110,8'b10101000,8'b00001000};
	if(yPixel>=(mouseY+17) && yPixel<(mouseY+18) && xPixel>=(mouseX+15) && xPixel<(mouseX+16)) {VGAr,VGAg,VGAb}={8'b01111100,8'b01101100,8'b00000100};
	if(yPixel>=(mouseY+17) && yPixel<(mouseY+18) && xPixel>=(mouseX+16) && xPixel<(mouseX+20)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+17) && yPixel<(mouseY+18) && xPixel>=(mouseX+20) && xPixel<(mouseX+21)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+17) && yPixel<(mouseY+18) && xPixel>=(mouseX+21) && xPixel<(mouseX+22)) {VGAr,VGAg,VGAb}={8'b11010000,8'b10111010,8'b00001000};
	if(yPixel>=(mouseY+18) && yPixel<(mouseY+19) && xPixel>=(mouseX+5) && xPixel<(mouseX+6)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+18) && yPixel<(mouseY+19) && xPixel>=(mouseX+6) && xPixel<(mouseX+7)) {VGAr,VGAg,VGAb}={8'b01110100,8'b01100100,8'b00000100};
	if(yPixel>=(mouseY+18) && yPixel<(mouseY+19) && xPixel>=(mouseX+7) && xPixel<(mouseX+8)) {VGAr,VGAg,VGAb}={8'b11011100,8'b11001010,8'b00001000};
	if(yPixel>=(mouseY+18) && yPixel<(mouseY+19) && xPixel>=(mouseX+8) && xPixel<(mouseX+11)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+18) && yPixel<(mouseY+19) && xPixel>=(mouseX+11) && xPixel<(mouseX+12)) {VGAr,VGAg,VGAb}={8'b11010100,8'b11000000,8'b00001000};
	if(yPixel>=(mouseY+18) && yPixel<(mouseY+19) && xPixel>=(mouseX+12) && xPixel<(mouseX+14)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+18) && yPixel<(mouseY+19) && xPixel>=(mouseX+14) && xPixel<(mouseX+15)) {VGAr,VGAg,VGAb}={8'b00101000,8'b00100100,8'b00000010};
	if(yPixel>=(mouseY+18) && yPixel<(mouseY+19) && xPixel>=(mouseX+15) && xPixel<(mouseX+16)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+18) && yPixel<(mouseY+19) && xPixel>=(mouseX+16) && xPixel<(mouseX+17)) {VGAr,VGAg,VGAb}={8'b11010100,8'b11000000,8'b00001000};
	if(yPixel>=(mouseY+18) && yPixel<(mouseY+19) && xPixel>=(mouseX+17) && xPixel<(mouseX+19)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+18) && yPixel<(mouseY+19) && xPixel>=(mouseX+19) && xPixel<(mouseX+20)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+18) && yPixel<(mouseY+19) && xPixel>=(mouseX+20) && xPixel<(mouseX+21)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+19) && yPixel<(mouseY+20) && xPixel>=(mouseX+5) && xPixel<(mouseX+6)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+19) && yPixel<(mouseY+20) && xPixel>=(mouseX+6) && xPixel<(mouseX+7)) {VGAr,VGAg,VGAb}={8'b00101010,8'b00100100,8'b00000010};
	if(yPixel>=(mouseY+19) && yPixel<(mouseY+20) && xPixel>=(mouseX+7) && xPixel<(mouseX+8)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+19) && yPixel<(mouseY+20) && xPixel>=(mouseX+8) && xPixel<(mouseX+12)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+19) && yPixel<(mouseY+20) && xPixel>=(mouseX+12) && xPixel<(mouseX+14)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+19) && yPixel<(mouseY+20) && xPixel>=(mouseX+14) && xPixel<(mouseX+15)) {VGAr,VGAg,VGAb}={8'b00101000,8'b00100100,8'b00000010};
	if(yPixel>=(mouseY+19) && yPixel<(mouseY+20) && xPixel>=(mouseX+15) && xPixel<(mouseX+17)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+19) && yPixel<(mouseY+20) && xPixel>=(mouseX+17) && xPixel<(mouseX+19)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+20) && yPixel<(mouseY+21) && xPixel>=(mouseX+6) && xPixel<(mouseX+7)) {VGAr,VGAg,VGAb}={8'b10100100,8'b10010000,8'b00000110};
	if(yPixel>=(mouseY+20) && yPixel<(mouseY+21) && xPixel>=(mouseX+7) && xPixel<(mouseX+8)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+20) && yPixel<(mouseY+21) && xPixel>=(mouseX+8) && xPixel<(mouseX+9)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+20) && yPixel<(mouseY+21) && xPixel>=(mouseX+9) && xPixel<(mouseX+12)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+20) && yPixel<(mouseY+21) && xPixel>=(mouseX+12) && xPixel<(mouseX+14)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+20) && yPixel<(mouseY+21) && xPixel>=(mouseX+14) && xPixel<(mouseX+15)) {VGAr,VGAg,VGAb}={8'b00101000,8'b00100100,8'b00000010};
	if(yPixel>=(mouseY+20) && yPixel<(mouseY+21) && xPixel>=(mouseX+15) && xPixel<(mouseX+17)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+20) && yPixel<(mouseY+21) && xPixel>=(mouseX+17) && xPixel<(mouseX+19)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+21) && yPixel<(mouseY+22) && xPixel>=(mouseX+4) && xPixel<(mouseX+5)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+21) && yPixel<(mouseY+22) && xPixel>=(mouseX+5) && xPixel<(mouseX+6)) {VGAr,VGAg,VGAb}={8'b10100100,8'b10010000,8'b00000110};
	if(yPixel>=(mouseY+21) && yPixel<(mouseY+22) && xPixel>=(mouseX+6) && xPixel<(mouseX+7)) {VGAr,VGAg,VGAb}={8'b01001100,8'b01000100,8'b00000100};
	if(yPixel>=(mouseY+21) && yPixel<(mouseY+22) && xPixel>=(mouseX+7) && xPixel<(mouseX+8)) {VGAr,VGAg,VGAb}={8'b11010110,8'b11000000,8'b00001000};
	if(yPixel>=(mouseY+21) && yPixel<(mouseY+22) && xPixel>=(mouseX+8) && xPixel<(mouseX+9)) {VGAr,VGAg,VGAb}={8'b10100100,8'b10010000,8'b00000110};
	if(yPixel>=(mouseY+21) && yPixel<(mouseY+22) && xPixel>=(mouseX+9) && xPixel<(mouseX+10)) {VGAr,VGAg,VGAb}={8'b10001100,8'b01111100,8'b00000100};
	if(yPixel>=(mouseY+21) && yPixel<(mouseY+22) && xPixel>=(mouseX+10) && xPixel<(mouseX+14)) {VGAr,VGAg,VGAb}={8'b00101010,8'b00100100,8'b00000010};
	if(yPixel>=(mouseY+21) && yPixel<(mouseY+22) && xPixel>=(mouseX+14) && xPixel<(mouseX+15)) {VGAr,VGAg,VGAb}={8'b00100010,8'b00011100,8'b00000000};
	if(yPixel>=(mouseY+21) && yPixel<(mouseY+22) && xPixel>=(mouseX+15) && xPixel<(mouseX+16)) {VGAr,VGAg,VGAb}={8'b00101010,8'b00100100,8'b00000010};
	if(yPixel>=(mouseY+21) && yPixel<(mouseY+22) && xPixel>=(mouseX+16) && xPixel<(mouseX+17)) {VGAr,VGAg,VGAb}={8'b10101100,8'b10011000,8'b00000110};
	if(yPixel>=(mouseY+21) && yPixel<(mouseY+22) && xPixel>=(mouseX+17) && xPixel<(mouseX+18)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+21) && yPixel<(mouseY+22) && xPixel>=(mouseX+18) && xPixel<(mouseX+19)) {VGAr,VGAg,VGAb}={8'b10111100,8'b10100110,8'b00001000};
	if(yPixel>=(mouseY+22) && yPixel<(mouseY+23) && xPixel>=(mouseX+4) && xPixel<(mouseX+5)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+22) && yPixel<(mouseY+23) && xPixel>=(mouseX+5) && xPixel<(mouseX+6)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+22) && yPixel<(mouseY+23) && xPixel>=(mouseX+6) && xPixel<(mouseX+7)) {VGAr,VGAg,VGAb}={8'b10100100,8'b10010000,8'b00000110};
	if(yPixel>=(mouseY+22) && yPixel<(mouseY+23) && xPixel>=(mouseX+7) && xPixel<(mouseX+8)) {VGAr,VGAg,VGAb}={8'b11011100,8'b11001010,8'b00001000};
	if(yPixel>=(mouseY+22) && yPixel<(mouseY+23) && xPixel>=(mouseX+8) && xPixel<(mouseX+9)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+22) && yPixel<(mouseY+23) && xPixel>=(mouseX+9) && xPixel<(mouseX+10)) {VGAr,VGAg,VGAb}={8'b10100100,8'b10010000,8'b00000110};
	if(yPixel>=(mouseY+22) && yPixel<(mouseY+23) && xPixel>=(mouseX+10) && xPixel<(mouseX+16)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+22) && yPixel<(mouseY+23) && xPixel>=(mouseX+16) && xPixel<(mouseX+17)) {VGAr,VGAg,VGAb}={8'b10100100,8'b10010000,8'b00000110};
	if(yPixel>=(mouseY+22) && yPixel<(mouseY+23) && xPixel>=(mouseX+17) && xPixel<(mouseX+18)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+22) && yPixel<(mouseY+23) && xPixel>=(mouseX+18) && xPixel<(mouseX+19)) {VGAr,VGAg,VGAb}={8'b10000110,8'b01111100,8'b00000100};
	if(yPixel>=(mouseY+22) && yPixel<(mouseY+23) && xPixel>=(mouseX+19) && xPixel<(mouseX+20)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+23) && yPixel<(mouseY+24) && xPixel>=(mouseX+4) && xPixel<(mouseX+6)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+23) && yPixel<(mouseY+24) && xPixel>=(mouseX+6) && xPixel<(mouseX+7)) {VGAr,VGAg,VGAb}={8'b01100100,8'b01011000,8'b00000100};
	if(yPixel>=(mouseY+23) && yPixel<(mouseY+24) && xPixel>=(mouseX+7) && xPixel<(mouseX+8)) {VGAr,VGAg,VGAb}={8'b11001110,8'b10110100,8'b00001000};
	if(yPixel>=(mouseY+23) && yPixel<(mouseY+24) && xPixel>=(mouseX+8) && xPixel<(mouseX+9)) {VGAr,VGAg,VGAb}={8'b10101100,8'b10011000,8'b00001000};
	if(yPixel>=(mouseY+23) && yPixel<(mouseY+24) && xPixel>=(mouseX+9) && xPixel<(mouseX+16)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+23) && yPixel<(mouseY+24) && xPixel>=(mouseX+16) && xPixel<(mouseX+17)) {VGAr,VGAg,VGAb}={8'b10100100,8'b10010000,8'b00000110};
	if(yPixel>=(mouseY+23) && yPixel<(mouseY+24) && xPixel>=(mouseX+17) && xPixel<(mouseX+18)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+23) && yPixel<(mouseY+24) && xPixel>=(mouseX+18) && xPixel<(mouseX+19)) {VGAr,VGAg,VGAb}={8'b11011110,8'b11001110,8'b00001000};
	if(yPixel>=(mouseY+24) && yPixel<(mouseY+25) && xPixel>=(mouseX+6) && xPixel<(mouseX+18)) {VGAr,VGAg,VGAb}={8'b00000000,8'b00000000,8'b00000000};
	if(yPixel>=(mouseY+24) && yPixel<(mouseY+25) && xPixel>=(mouseX+18) && xPixel<(mouseX+19)) {VGAr,VGAg,VGAb}={8'b10100100,8'b10010000,8'b00000110};

	//Drawing Solid shape "test"
	if(xPixel>=testX && xPixel<=testX+404 && yPixel>=testY && yPixel<=testY+184)
	begin
		VGAr = 8'b01011011;
		VGAg = 8'b10011011;
		VGAb = 8'b11010101;
		if(xPixel<testX+1 || xPixel>testX+403 || yPixel<testY+1 || yPixel>testY+183)    //Drawing border
		begin
			VGAr = 8'b01000001;
			VGAg = 8'b01110001;
			VGAb = 8'b10011100;
		end
	end

end

wire [9:0]peterX;
wire [9:0]peterY;
wire [9:0]einsteinX;
wire [9:0]einsteinY;
wire [9:0]testX;
wire [9:0]testY;
wire [9:0]BasictransparencyX;
wire [9:0]BasictransparencyY;
wire [9:0]bouncerX;
wire [9:0]bouncerY;
wire [9:0]bouncerVISIBLE;


animations anim1(animationCLOCK,reset,wasd,arrows,BasictransparencyX,BasictransparencyY,bouncerX,bouncerY,peterX,peterY,einsteinX,einsteinY,testX,testY);
wire [15:0]einsteinq;
rameinstein einsteinram((((yPixel-einsteinY+einsteinSKIPY)/1)*(139) +(((xPixel-einsteinX)/1))+(einsteinSKIPX/1)+((139)*(einsteinsp))),CLOCK,16'd0,0,einsteinq);
wire [15:0]peterq;
rampeter peterram((((yPixel-peterY+peterSKIPY)/1)*(156) +(((xPixel-peterX)/1))+(peterSKIPX/1)+((156)*(petersp))),CLOCK,16'd0,0,peterq);
wire [15:0]bouncerq;
rambouncer bouncerram((((yPixel-bouncerY+bouncerSKIPY)/1)*(303) +(((xPixel-bouncerX)/1))+(bouncerSKIPX/1)+((303)*(bouncersp))),CLOCK,16'd0,0,bouncerq);

	assign colgeniuses=((einsteinY+156>peterY) && (einsteinY<peterY+156) && (einsteinX+139>peterX) && (einsteinX<peterX+156));

endmodule

module animations(animationCLOCK,reset,wasd,arrows,BasictransparencyX,BasictransparencyY,bouncerX,bouncerY,peterX,peterY,einsteinX,einsteinY,testX,testY);

input reset;
output [9:0]peterX;
reg [9:0]peterX;
output [9:0]peterY;
reg [9:0]peterY;
output [9:0]einsteinX;
reg [9:0]einsteinX;
output [9:0]einsteinY;
reg [9:0]einsteinY;
output [9:0]testX;
reg [9:0]testX;
output [9:0]testY;
reg [9:0]testY;
output [9:0]BasictransparencyX;
reg [9:0]BasictransparencyX;
reg BasictransparencyXDir;
output [9:0]BasictransparencyY;
reg [9:0]BasictransparencyY;
reg BasictransparencyYDir;
output [9:0]bouncerX;
reg [9:0]bouncerX;
reg bouncerXDir;
output [9:0]bouncerY;
reg [9:0]bouncerY;
reg bouncerYDir;
input animationCLOCK;
input [3:0]arrows;
input [3:0]wasd;
reg initilized;

initial begin
	einsteinX=84;
	einsteinY=295;
	BasictransparencyX=12;
	BasictransparencyY=190;
	peterX=242;
	peterY=230;
	bouncerX=223;
	bouncerY=34;
	testX=178;
	testY=198;
end


always @ (posedge animationCLOCK)
begin
	//Writing WASD movement for einsteinX:
	if(wasd[1]==1 && einsteinX>100) einsteinX=einsteinX-15;
	if (wasd[3] == 1 && einsteinX < 600 - 139) einsteinX = einsteinX + 15;
	if(wasd[0]==1 && einsteinY>100) einsteinY=einsteinY-15;
	if(wasd[2]==1 && einsteinY<400-156) einsteinY=einsteinY+15;
	//Writing WASD movement for testX:
	if(wasd[1]==1 && testX>0) testX=testX-1;
	if (wasd[3] == 1 && testX < 640 - 404) testX = testX + 1;
	if(wasd[0]==1 && testY>0) testY=testY-1;
	if(wasd[2]==1 && testY<480-184) testY=testY+1;

	//Writing ARROWS movement for peterX:
	if(arrows[1]==1 && peterX>200) peterX=peterX-5;
	if (arrows[3] == 1 && peterX < 500 - 156) peterX = peterX + 5;
	if(arrows[0]==1 && peterY>0) peterY=peterY-5;
	if(arrows[2]==1 && peterY<480-156) peterY=peterY+5;

	//Writing Bouncing movement for BasictransparencyX:
	if(BasictransparencyXDir==1)
	begin
		if (BasictransparencyX >= 640 - 130)
		begin
			BasictransparencyXDir = 0;
		end
		else
		begin
			BasictransparencyX <= BasictransparencyX + 10;
		end
	end
	else
	begin
		if (BasictransparencyX <= 0)
		begin
			BasictransparencyXDir = 1;
		end
		else
		begin
			BasictransparencyX <= BasictransparencyX - 10;
		end
	end
	if(BasictransparencyYDir==1)
	begin
		if (BasictransparencyY >= 480 - 68)
		begin
			BasictransparencyYDir = 0;
		end
		else
		begin
			BasictransparencyY <= BasictransparencyY + 10;
		end
	end
	else
	begin
		if (BasictransparencyY <= 0)
		begin
			BasictransparencyYDir = 1;
		end
		else
		begin
			BasictransparencyY <= BasictransparencyY - 10;
		end
	end
	//Writing Bouncing movement for bouncerX:
	if(bouncerXDir==1)
	begin
		if (bouncerX >= 540 - 303)
		begin
			bouncerXDir = 0;
		end
		else
		begin
			bouncerX <= bouncerX + 1;
		end
	end
	else
	begin
		if (bouncerX <= 100)
		begin
			bouncerXDir = 1;
		end
		else
		begin
			bouncerX <= bouncerX - 1;
		end
	end
	if(bouncerYDir==1)
	begin
		if (bouncerY >= 380 - 171)
		begin
			bouncerYDir = 0;
		end
		else
		begin
			bouncerY <= bouncerY + 1;
		end
	end
	else
	begin
		if (bouncerY <= 100)
		begin
			bouncerYDir = 1;
		end
		else
		begin
			bouncerY <= bouncerY - 1;
		end
	end
end

endmodule
